name: 🚀 Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Для подписанного APK нужно добавить secrets в репозиторий:
    # SETTINGS -> Secrets and variables -> Actions -> New repository secret
    # - KEYSTORE_BASE64 (base64 keystore файла)
    # - KEYSTORE_PASSWORD
    # - KEY_ALIAS
    # - KEY_PASSWORD
    
    - name: Decode Keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        echo "$KEYSTORE_BASE64" | base64 -d > app/keystore.jks

    - name: Build Signed APK
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew assembleRelease

    - name: Upload APK to Release
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/*.apk
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
